### ISSUE TITLE
Can't find downloadDataset.pl

### ISSUE THREAD

**Issue by mshakya** [WGS-standards-and-analysis/datasets#3]
Hi,

I am trying to download the dataset listed but I cant find the perl script as shown in README. Where can I find it? There are other perl scripts in the scripts folder but not `downloadDataset.pl`.

Thank you

**Comment by lskatz** [comment]
This is just a few hours after I started a round of editing, wow!  I am so flattered for our team that this project has had a lot of attention!  

We'll get back on track today or tomorrow but the only real change has been that `downloadDataset.pl` is being changed to `GenFSGopher.pl`.  For stable versions please check out the releases tab.  Keep rocking with the datasets and I promise to be back on track soon and with a new release!

**Comment by lskatz** [comment]
Documentation fixed in 1ca45c49d9cc8f0deb97baf7543389d07a69d292

**Comment by tseemann** [comment]
@lskatz hopefully this doesn't cause the paper to be rejected :-/

**Comment by lskatz** [comment]
This comment and many others will make the paper stronger, and we appreciate them.
